More readable error messages
For example, instead of 

Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })

print

error: FASTA file cannot be parsed: FASTA file must start with '>'