Nicer errors when parsing invalid FASTQ files
... by introducing a FastqError enum.

Example error messages:

error: FASTQ file cannot be parsed: Record must start with '@', but found '>'

error: FASTQ file cannot be parsed: Found 301 nucleotides but 298 quality values in record 'SRR1377138.2'